import Link from "next/link";
import {
  Sparkles, MessageSquareText, PieChart, Wallet, ArrowRight,
  ScanLine, BellRing, LineChart as LineChartIcon,
} from "lucide-react";

const FEATURES = [
  {
    icon: ScanLine,
    title: "Natural-language entry",
    desc: "Type \"₹450 on dinner yesterday\" and let Gemini turn it into a structured, editable expense.",
  },
  {
    icon: PieChart,
    title: "Automatic categorization",
    desc: "Every expense is sorted into a clear category, with AI suggestions you can always override.",
  },
  {
    icon: LineChartIcon,
    title: "Real charts, real data",
    desc: "Category, trend and budget charts are drawn straight from your own stored transactions.",
  },
  {
    icon: MessageSquareText,
    title: "FinAI conversational assistant",
    desc: "Ask plain-language questions about your spending and get answers grounded in your data.",
  },
  {
    icon: Wallet,
    title: "Budget tracking",
    desc: "Set a monthly budget and see at a glance whether you're under, near, or over it.",
  },
  {
    icon: BellRing,
    title: "AI monthly summaries",
    desc: "A narrative recap of the month — numbers computed in code, explanation generated by AI.",
  },
];

const STEPS = [
  { title: "Log an expense", desc: "Add it manually, or just describe it in plain English." },
  { title: "Let AI structure it", desc: "Gemini extracts amount, category and date — you review before saving." },
  { title: "See it everywhere", desc: "Dashboard, analytics and the FinAI assistant update from the same data." },
];

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-slate-50">
      <header className="mx-auto flex max-w-6xl items-center justify-between px-6 py-6">
        <div className="flex items-center gap-2 text-slate-900">
          <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-brand-600 text-white">
            <Wallet className="h-[18px] w-[18px]" />
          </div>
          <span className="text-sm font-semibold">Finance Assistant</span>
        </div>
        <Link
          href="/dashboard"
          className="rounded-lg bg-brand-600 px-4 py-2 text-sm font-medium text-white hover:bg-brand-700"
        >
          Open App
        </Link>
      </header>

      {/* Hero */}
      <section className="mx-auto max-w-4xl px-6 pb-16 pt-10 text-center">
        <span className="inline-flex items-center gap-1.5 rounded-full border border-brand-200 bg-brand-50 px-3 py-1 text-xs font-medium text-brand-700">
          <Sparkles className="h-3.5 w-3.5" /> Student project · Powered by Google Gemini
        </span>
        <h1 className="mt-5 text-4xl font-semibold tracking-tight text-slate-900 sm:text-5xl">
          Intelligent Personal Finance Assistant
        </h1>
        <p className="mx-auto mt-4 max-w-2xl text-lg text-slate-600">
          Log expenses in plain English, watch them get categorized automatically, and ask an
          AI assistant plain-language questions about your own spending — grounded entirely in
          your real transaction data.
        </p>
        <div className="mt-8 flex justify-center gap-3">
          <Link
            href="/dashboard"
            className="inline-flex items-center gap-2 rounded-xl bg-brand-600 px-5 py-3 text-sm font-semibold text-white hover:bg-brand-700"
          >
            Get Started <ArrowRight className="h-4 w-4" />
          </Link>
          <Link
            href="/assistant"
            className="inline-flex items-center gap-2 rounded-xl border border-slate-300 bg-white px-5 py-3 text-sm font-semibold text-slate-700 hover:bg-slate-50"
          >
            Try FinAI Assistant
          </Link>
        </div>
        <p className="mt-4 text-xs text-slate-400">
          Academic project — informational only, not a substitute for professional financial advice.
        </p>
      </section>

      {/* Dashboard preview */}
      <section className="mx-auto max-w-5xl px-6 pb-16">
        <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-card sm:p-6">
          <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
            {[
              { label: "Total Spending", value: "₹18,450" },
              { label: "Monthly Budget", value: "₹25,000" },
              { label: "Remaining", value: "₹6,550" },
              { label: "Transactions", value: "14" },
            ].map((s) => (
              <div key={s.label} className="rounded-xl bg-slate-50 p-4">
                <p className="text-xs text-slate-500">{s.label}</p>
                <p className="mt-1 text-lg font-semibold text-slate-900">{s.value}</p>
              </div>
            ))}
          </div>
          <div className="mt-3 h-3 w-full overflow-hidden rounded-full bg-slate-100">
            <div className="h-full w-[74%] rounded-full bg-emerald-500" />
          </div>
          <p className="mt-2 text-xs text-slate-500">74% of monthly budget used — Under Budget (illustrative preview)</p>
        </div>
      </section>

      {/* Features */}
      <section className="mx-auto max-w-6xl px-6 pb-16">
        <h2 className="text-center text-2xl font-semibold text-slate-900">Everything you need to understand your spending</h2>
        <div className="mt-8 grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">
          {FEATURES.map((f) => (
            <div key={f.title} className="rounded-2xl border border-slate-200 bg-white p-5">
              <div className="mb-3 flex h-9 w-9 items-center justify-center rounded-lg bg-brand-50 text-brand-600">
                <f.icon className="h-[18px] w-[18px]" />
              </div>
              <h3 className="text-sm font-semibold text-slate-900">{f.title}</h3>
              <p className="mt-1 text-sm text-slate-500">{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* How it works */}
      <section className="mx-auto max-w-4xl px-6 pb-20">
        <h2 className="text-center text-2xl font-semibold text-slate-900">How it works</h2>
        <div className="mt-8 grid grid-cols-1 gap-6 sm:grid-cols-3">
          {STEPS.map((s, i) => (
            <div key={s.title} className="text-center">
              <div className="mx-auto mb-3 flex h-10 w-10 items-center justify-center rounded-full bg-brand-600 text-sm font-semibold text-white">
                {i + 1}
              </div>
              <h3 className="text-sm font-semibold text-slate-900">{s.title}</h3>
              <p className="mt-1 text-sm text-slate-500">{s.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="mx-auto max-w-3xl px-6 pb-24 text-center">
        <div className="rounded-2xl bg-brand-600 px-8 py-12 text-white">
          <h2 className="text-2xl font-semibold">Ready to see where your money goes?</h2>
          <p className="mt-2 text-brand-100">Open the dashboard and load demo data to explore every feature in minutes.</p>
          <Link
            href="/dashboard"
            className="mt-6 inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-semibold text-brand-700 hover:bg-brand-50"
          >
            Open Dashboard <ArrowRight className="h-4 w-4" />
          </Link>
        </div>
      </section>

      <footer className="border-t border-slate-200 py-6 text-center text-xs text-slate-400">
        Intelligent Personal Finance Assistant — a student project. Not professional financial advice.
      </footer>
    </div>
  );
}
